/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LegisFacileGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class LeiElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Lei");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsTypeParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Lei:
		//	elements+=Type*;
		@Override public ParserRule getRule() { return rule; }
		
		//elements+=Type*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//Type
		public RuleCall getElementsTypeParserRuleCall_0() { return cElementsTypeParserRuleCall_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDataTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEntityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cPreliminarAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cPreliminarPreliminarParserRuleCall_2_0_0 = (RuleCall)cPreliminarAssignment_2_0.eContents().get(0);
		private final Assignment cNormativaAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNormativaNormativaParserRuleCall_2_1_0 = (RuleCall)cNormativaAssignment_2_1.eContents().get(0);
		private final Assignment cFinalAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cFinalFinalParserRuleCall_2_2_0 = (RuleCall)cFinalAssignment_2_2.eContents().get(0);
		
		//Type:
		//	DataType | Entity | preliminar=Preliminar normativa=Normativa final=Final;
		@Override public ParserRule getRule() { return rule; }
		
		//DataType | Entity | preliminar=Preliminar normativa=Normativa final=Final
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DataType
		public RuleCall getDataTypeParserRuleCall_0() { return cDataTypeParserRuleCall_0; }
		
		//Entity
		public RuleCall getEntityParserRuleCall_1() { return cEntityParserRuleCall_1; }
		
		//preliminar=Preliminar normativa=Normativa final=Final
		public Group getGroup_2() { return cGroup_2; }
		
		//preliminar=Preliminar
		public Assignment getPreliminarAssignment_2_0() { return cPreliminarAssignment_2_0; }
		
		//Preliminar
		public RuleCall getPreliminarPreliminarParserRuleCall_2_0_0() { return cPreliminarPreliminarParserRuleCall_2_0_0; }
		
		//normativa=Normativa
		public Assignment getNormativaAssignment_2_1() { return cNormativaAssignment_2_1; }
		
		//Normativa
		public RuleCall getNormativaNormativaParserRuleCall_2_1_0() { return cNormativaNormativaParserRuleCall_2_1_0; }
		
		//final=Final
		public Assignment getFinalAssignment_2_2() { return cFinalAssignment_2_2; }
		
		//Final
		public RuleCall getFinalFinalParserRuleCall_2_2_0() { return cFinalFinalParserRuleCall_2_2_0; }
	}
	public class PreliminarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Preliminar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cPreliminarKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cPreliminarKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEpigrageAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEpigrageEpigrafeParserRuleCall_2_0 = (RuleCall)cEpigrageAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEmentaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEmentaEmentaParserRuleCall_4_0 = (RuleCall)cEmentaAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPreambuloAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPreambuloPreambuloParserRuleCall_6_0 = (RuleCall)cPreambuloAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Preliminar:
		//	('Preliminar' | 'preliminar') '{'
		//	epigrage=Epigrafe ','
		//	ementa=Ementa ','
		//	preambulo=Preambulo ','
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//('Preliminar' | 'preliminar') '{' epigrage=Epigrafe ',' ementa=Ementa ',' preambulo=Preambulo ',' '}'
		public Group getGroup() { return cGroup; }
		
		//('Preliminar' | 'preliminar')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Preliminar'
		public Keyword getPreliminarKeyword_0_0() { return cPreliminarKeyword_0_0; }
		
		//'preliminar'
		public Keyword getPreliminarKeyword_0_1() { return cPreliminarKeyword_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//epigrage=Epigrafe
		public Assignment getEpigrageAssignment_2() { return cEpigrageAssignment_2; }
		
		//Epigrafe
		public RuleCall getEpigrageEpigrafeParserRuleCall_2_0() { return cEpigrageEpigrafeParserRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//ementa=Ementa
		public Assignment getEmentaAssignment_4() { return cEmentaAssignment_4; }
		
		//Ementa
		public RuleCall getEmentaEmentaParserRuleCall_4_0() { return cEmentaEmentaParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//preambulo=Preambulo
		public Assignment getPreambuloAssignment_6() { return cPreambuloAssignment_6; }
		
		//Preambulo
		public RuleCall getPreambuloPreambuloParserRuleCall_6_0() { return cPreambuloPreambuloParserRuleCall_6_0; }
		
		//','
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EpigrafeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Epigrafe");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cEpigrafeKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cEpigrafeKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAtoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAtoSTRINGTerminalRuleCall_2_0 = (RuleCall)cAtoAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNumeroAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNumeroINTTerminalRuleCall_4_0 = (RuleCall)cNumeroAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAnoAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAnoINTTerminalRuleCall_6_0 = (RuleCall)cAnoAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Epigrafe:
		//	('Epigrafe' | 'epigrafe') '(' ato=STRING ',' numero=INT ',' ano=INT ')';
		@Override public ParserRule getRule() { return rule; }
		
		//('Epigrafe' | 'epigrafe') '(' ato=STRING ',' numero=INT ',' ano=INT ')'
		public Group getGroup() { return cGroup; }
		
		//('Epigrafe' | 'epigrafe')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Epigrafe'
		public Keyword getEpigrafeKeyword_0_0() { return cEpigrafeKeyword_0_0; }
		
		//'epigrafe'
		public Keyword getEpigrafeKeyword_0_1() { return cEpigrafeKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//ato=STRING
		public Assignment getAtoAssignment_2() { return cAtoAssignment_2; }
		
		//STRING
		public RuleCall getAtoSTRINGTerminalRuleCall_2_0() { return cAtoSTRINGTerminalRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//numero=INT
		public Assignment getNumeroAssignment_4() { return cNumeroAssignment_4; }
		
		//INT
		public RuleCall getNumeroINTTerminalRuleCall_4_0() { return cNumeroINTTerminalRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//ano=INT
		public Assignment getAnoAssignment_6() { return cAnoAssignment_6; }
		
		//INT
		public RuleCall getAnoINTTerminalRuleCall_6_0() { return cAnoINTTerminalRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class EmentaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Ementa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cEmentaKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cEmentaKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEmentaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEmentaSTRINGTerminalRuleCall_2_0 = (RuleCall)cEmentaAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Ementa:
		//	('Ementa' | 'ementa') '(' ementa=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//('Ementa' | 'ementa') '(' ementa=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//('Ementa' | 'ementa')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Ementa'
		public Keyword getEmentaKeyword_0_0() { return cEmentaKeyword_0_0; }
		
		//'ementa'
		public Keyword getEmentaKeyword_0_1() { return cEmentaKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//ementa=STRING
		public Assignment getEmentaAssignment_2() { return cEmentaAssignment_2; }
		
		//STRING
		public RuleCall getEmentaSTRINGTerminalRuleCall_2_0() { return cEmentaSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class PreambuloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Preambulo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cPreambuloKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cPreambuloKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPreambuloAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPreambuloSTRINGTerminalRuleCall_2_0 = (RuleCall)cPreambuloAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Preambulo:
		//	('Preambulo' | 'preambulo') '(' preambulo=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//('Preambulo' | 'preambulo') '(' preambulo=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//('Preambulo' | 'preambulo')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Preambulo'
		public Keyword getPreambuloKeyword_0_0() { return cPreambuloKeyword_0_0; }
		
		//'preambulo'
		public Keyword getPreambuloKeyword_0_1() { return cPreambuloKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//preambulo=STRING
		public Assignment getPreambuloAssignment_2() { return cPreambuloAssignment_2; }
		
		//STRING
		public RuleCall getPreambuloSTRINGTerminalRuleCall_2_0() { return cPreambuloSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class NormativaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Normativa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cNormativaKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cNormativaKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cArtigosAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cArtigosArtigoParserRuleCall_2_0 = (RuleCall)cArtigosAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Normativa:
		//	('Normativa' | 'normativa') '{'
		//	artigos+=Artigo+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//('Normativa' | 'normativa') '{' artigos+=Artigo+ '}'
		public Group getGroup() { return cGroup; }
		
		//('Normativa' | 'normativa')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Normativa'
		public Keyword getNormativaKeyword_0_0() { return cNormativaKeyword_0_0; }
		
		//'normativa'
		public Keyword getNormativaKeyword_0_1() { return cNormativaKeyword_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//artigos+=Artigo+
		public Assignment getArtigosAssignment_2() { return cArtigosAssignment_2; }
		
		//Artigo
		public RuleCall getArtigosArtigoParserRuleCall_2_0() { return cArtigosArtigoParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ArtigoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Artigo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cArtigoKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cArtigoKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCaputAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cCaputCaputParserRuleCall_2_0 = (RuleCall)cCaputAssignment_2.eContents().get(0);
		private final Assignment cParagrafosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParagrafosParagrafoParserRuleCall_3_0 = (RuleCall)cParagrafosAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Artigo:
		//	('Artigo' | 'artigo') '{'
		//	caput=Caput
		//	paragrafos+=Paragrafo*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//('Artigo' | 'artigo') '{' caput=Caput paragrafos+=Paragrafo* '}'
		public Group getGroup() { return cGroup; }
		
		//('Artigo' | 'artigo')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Artigo'
		public Keyword getArtigoKeyword_0_0() { return cArtigoKeyword_0_0; }
		
		//'artigo'
		public Keyword getArtigoKeyword_0_1() { return cArtigoKeyword_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//caput=Caput
		public Assignment getCaputAssignment_2() { return cCaputAssignment_2; }
		
		//Caput
		public RuleCall getCaputCaputParserRuleCall_2_0() { return cCaputCaputParserRuleCall_2_0; }
		
		//paragrafos+=Paragrafo*
		public Assignment getParagrafosAssignment_3() { return cParagrafosAssignment_3; }
		
		//Paragrafo
		public RuleCall getParagrafosParagrafoParserRuleCall_3_0() { return cParagrafosParagrafoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class CaputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Caput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cCaputKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cCaputKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextoSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextoAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIncisosAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIncisosIncisoParserRuleCall_4_1_0 = (RuleCall)cIncisosAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//Caput:
		//	('Caput' | 'caput') '(' texto=STRING ')' ('{'
		//	incisos+=Inciso*
		//	'}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//('Caput' | 'caput') '(' texto=STRING ')' ('{' incisos+=Inciso* '}')?
		public Group getGroup() { return cGroup; }
		
		//('Caput' | 'caput')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Caput'
		public Keyword getCaputKeyword_0_0() { return cCaputKeyword_0_0; }
		
		//'caput'
		public Keyword getCaputKeyword_0_1() { return cCaputKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//texto=STRING
		public Assignment getTextoAssignment_2() { return cTextoAssignment_2; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_2_0() { return cTextoSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//('{' incisos+=Inciso* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//incisos+=Inciso*
		public Assignment getIncisosAssignment_4_1() { return cIncisosAssignment_4_1; }
		
		//Inciso
		public RuleCall getIncisosIncisoParserRuleCall_4_1_0() { return cIncisosIncisoParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}
	public class ParagrafoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Paragrafo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cParagrafoKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cParagrafoKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextoSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextoAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIncisosAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIncisosIncisoParserRuleCall_4_1_0 = (RuleCall)cIncisosAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//Paragrafo:
		//	('Paragrafo' | 'paragrafo') '(' texto=STRING ')' ('{'
		//	incisos+=Inciso*
		//	'}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//('Paragrafo' | 'paragrafo') '(' texto=STRING ')' ('{' incisos+=Inciso* '}')?
		public Group getGroup() { return cGroup; }
		
		//('Paragrafo' | 'paragrafo')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Paragrafo'
		public Keyword getParagrafoKeyword_0_0() { return cParagrafoKeyword_0_0; }
		
		//'paragrafo'
		public Keyword getParagrafoKeyword_0_1() { return cParagrafoKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//texto=STRING
		public Assignment getTextoAssignment_2() { return cTextoAssignment_2; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_2_0() { return cTextoSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//('{' incisos+=Inciso* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//incisos+=Inciso*
		public Assignment getIncisosAssignment_4_1() { return cIncisosAssignment_4_1; }
		
		//Inciso
		public RuleCall getIncisosIncisoParserRuleCall_4_1_0() { return cIncisosIncisoParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}
	public class IncisoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Inciso");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cIncisoKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cIncisoKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextoSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextoAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAlineasAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAlineasAlineaParserRuleCall_4_1_0 = (RuleCall)cAlineasAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//Inciso:
		//	('Inciso' | 'inciso') '(' texto=STRING ')' ('{'
		//	alineas+=Alinea*
		//	'}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//('Inciso' | 'inciso') '(' texto=STRING ')' ('{' alineas+=Alinea* '}')?
		public Group getGroup() { return cGroup; }
		
		//('Inciso' | 'inciso')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Inciso'
		public Keyword getIncisoKeyword_0_0() { return cIncisoKeyword_0_0; }
		
		//'inciso'
		public Keyword getIncisoKeyword_0_1() { return cIncisoKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//texto=STRING
		public Assignment getTextoAssignment_2() { return cTextoAssignment_2; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_2_0() { return cTextoSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//('{' alineas+=Alinea* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//alineas+=Alinea*
		public Assignment getAlineasAssignment_4_1() { return cAlineasAssignment_4_1; }
		
		//Alinea
		public RuleCall getAlineasAlineaParserRuleCall_4_1_0() { return cAlineasAlineaParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}
	public class AlineaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Alinea");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cAlineaKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cAlineaKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextoSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextoAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cItensAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cItensItemParserRuleCall_4_1_0 = (RuleCall)cItensAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//Alinea:
		//	('alinea' | 'Alinea') '(' texto=STRING ')' ('{'
		//	itens+=Item*
		//	'}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//('alinea' | 'Alinea') '(' texto=STRING ')' ('{' itens+=Item* '}')?
		public Group getGroup() { return cGroup; }
		
		//('alinea' | 'Alinea')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'alinea'
		public Keyword getAlineaKeyword_0_0() { return cAlineaKeyword_0_0; }
		
		//'Alinea'
		public Keyword getAlineaKeyword_0_1() { return cAlineaKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//texto=STRING
		public Assignment getTextoAssignment_2() { return cTextoAssignment_2; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_2_0() { return cTextoSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//('{' itens+=Item* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//itens+=Item*
		public Assignment getItensAssignment_4_1() { return cItensAssignment_4_1; }
		
		//Item
		public RuleCall getItensItemParserRuleCall_4_1_0() { return cItensItemParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_2() { return cRightCurlyBracketKeyword_4_2; }
	}
	public class ItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Item");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cItemKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cItemKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextoSTRINGTerminalRuleCall_2_0 = (RuleCall)cTextoAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Item:
		//	('Item' | 'item') '(' texto=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//('Item' | 'item') '(' texto=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//('Item' | 'item')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Item'
		public Keyword getItemKeyword_0_0() { return cItemKeyword_0_0; }
		
		//'item'
		public Keyword getItemKeyword_0_1() { return cItemKeyword_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//texto=STRING
		public Assignment getTextoAssignment_2() { return cTextoAssignment_2; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_2_0() { return cTextoSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class FinalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Final");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cFinalKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cFinalKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Final:
		//	('Final' | 'final') '{'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//('Final' | 'final') '{' '}'
		public Group getGroup() { return cGroup; }
		
		//('Final' | 'final')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'Final'
		public Keyword getFinalKeyword_0_0() { return cFinalKeyword_0_0; }
		
		//'final'
		public Keyword getFinalKeyword_0_1() { return cFinalKeyword_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	public class DataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.DataType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDatatypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//DataType:
		//	'datatype' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'datatype' name=ID
		public Group getGroup() { return cGroup; }
		
		//'datatype'
		public Keyword getDatatypeKeyword_0() { return cDatatypeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeEntityCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeEntityIDTerminalRuleCall_2_1_0_1 = (RuleCall)cSuperTypeEntityCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeaturesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFeaturesFeatureParserRuleCall_4_0 = (RuleCall)cFeaturesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Entity:
		//	'entity' name=ID ('extends' superType=[Entity])? '{'
		//	features+=Feature*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'entity' name=ID ('extends' superType=[Entity])? '{' features+=Feature* '}'
		public Group getGroup() { return cGroup; }
		
		//'entity'
		public Keyword getEntityKeyword_0() { return cEntityKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('extends' superType=[Entity])?
		public Group getGroup_2() { return cGroup_2; }
		
		//'extends'
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }
		
		//superType=[Entity]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }
		
		//[Entity]
		public CrossReference getSuperTypeEntityCrossReference_2_1_0() { return cSuperTypeEntityCrossReference_2_1_0; }
		
		//ID
		public RuleCall getSuperTypeEntityIDTerminalRuleCall_2_1_0_1() { return cSuperTypeEntityIDTerminalRuleCall_2_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//features+=Feature*
		public Assignment getFeaturesAssignment_4() { return cFeaturesAssignment_4; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_4_0() { return cFeaturesFeatureParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ufes.mdd.lei.LegisFacile.Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cManyAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cManyManyKeyword_0_0 = (Keyword)cManyAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTypeTypeCrossReference_3_0 = (CrossReference)cTypeAssignment_3.eContents().get(0);
		private final RuleCall cTypeTypeIDTerminalRuleCall_3_0_1 = (RuleCall)cTypeTypeCrossReference_3_0.eContents().get(1);
		
		//Feature:
		//	many?='many'? name=ID ':' type=[Type];
		@Override public ParserRule getRule() { return rule; }
		
		//many?='many'? name=ID ':' type=[Type]
		public Group getGroup() { return cGroup; }
		
		//many?='many'?
		public Assignment getManyAssignment_0() { return cManyAssignment_0; }
		
		//'many'
		public Keyword getManyManyKeyword_0_0() { return cManyManyKeyword_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//type=[Type]
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//[Type]
		public CrossReference getTypeTypeCrossReference_3_0() { return cTypeTypeCrossReference_3_0; }
		
		//ID
		public RuleCall getTypeTypeIDTerminalRuleCall_3_0_1() { return cTypeTypeIDTerminalRuleCall_3_0_1; }
	}
	
	
	private final LeiElements pLei;
	private final TypeElements pType;
	private final PreliminarElements pPreliminar;
	private final EpigrafeElements pEpigrafe;
	private final EmentaElements pEmenta;
	private final PreambuloElements pPreambulo;
	private final NormativaElements pNormativa;
	private final ArtigoElements pArtigo;
	private final CaputElements pCaput;
	private final ParagrafoElements pParagrafo;
	private final IncisoElements pInciso;
	private final AlineaElements pAlinea;
	private final ItemElements pItem;
	private final FinalElements pFinal;
	private final DataTypeElements pDataType;
	private final EntityElements pEntity;
	private final FeatureElements pFeature;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LegisFacileGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pLei = new LeiElements();
		this.pType = new TypeElements();
		this.pPreliminar = new PreliminarElements();
		this.pEpigrafe = new EpigrafeElements();
		this.pEmenta = new EmentaElements();
		this.pPreambulo = new PreambuloElements();
		this.pNormativa = new NormativaElements();
		this.pArtigo = new ArtigoElements();
		this.pCaput = new CaputElements();
		this.pParagrafo = new ParagrafoElements();
		this.pInciso = new IncisoElements();
		this.pAlinea = new AlineaElements();
		this.pItem = new ItemElements();
		this.pFinal = new FinalElements();
		this.pDataType = new DataTypeElements();
		this.pEntity = new EntityElements();
		this.pFeature = new FeatureElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ufes.mdd.lei.LegisFacile".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Lei:
	//	elements+=Type*;
	public LeiElements getLeiAccess() {
		return pLei;
	}
	
	public ParserRule getLeiRule() {
		return getLeiAccess().getRule();
	}
	
	//Type:
	//	DataType | Entity | preliminar=Preliminar normativa=Normativa final=Final;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Preliminar:
	//	('Preliminar' | 'preliminar') '{'
	//	epigrage=Epigrafe ','
	//	ementa=Ementa ','
	//	preambulo=Preambulo ','
	//	'}';
	public PreliminarElements getPreliminarAccess() {
		return pPreliminar;
	}
	
	public ParserRule getPreliminarRule() {
		return getPreliminarAccess().getRule();
	}
	
	//Epigrafe:
	//	('Epigrafe' | 'epigrafe') '(' ato=STRING ',' numero=INT ',' ano=INT ')';
	public EpigrafeElements getEpigrafeAccess() {
		return pEpigrafe;
	}
	
	public ParserRule getEpigrafeRule() {
		return getEpigrafeAccess().getRule();
	}
	
	//Ementa:
	//	('Ementa' | 'ementa') '(' ementa=STRING ')';
	public EmentaElements getEmentaAccess() {
		return pEmenta;
	}
	
	public ParserRule getEmentaRule() {
		return getEmentaAccess().getRule();
	}
	
	//Preambulo:
	//	('Preambulo' | 'preambulo') '(' preambulo=STRING ')';
	public PreambuloElements getPreambuloAccess() {
		return pPreambulo;
	}
	
	public ParserRule getPreambuloRule() {
		return getPreambuloAccess().getRule();
	}
	
	//Normativa:
	//	('Normativa' | 'normativa') '{'
	//	artigos+=Artigo+
	//	'}';
	public NormativaElements getNormativaAccess() {
		return pNormativa;
	}
	
	public ParserRule getNormativaRule() {
		return getNormativaAccess().getRule();
	}
	
	//Artigo:
	//	('Artigo' | 'artigo') '{'
	//	caput=Caput
	//	paragrafos+=Paragrafo*
	//	'}';
	public ArtigoElements getArtigoAccess() {
		return pArtigo;
	}
	
	public ParserRule getArtigoRule() {
		return getArtigoAccess().getRule();
	}
	
	//Caput:
	//	('Caput' | 'caput') '(' texto=STRING ')' ('{'
	//	incisos+=Inciso*
	//	'}')?;
	public CaputElements getCaputAccess() {
		return pCaput;
	}
	
	public ParserRule getCaputRule() {
		return getCaputAccess().getRule();
	}
	
	//Paragrafo:
	//	('Paragrafo' | 'paragrafo') '(' texto=STRING ')' ('{'
	//	incisos+=Inciso*
	//	'}')?;
	public ParagrafoElements getParagrafoAccess() {
		return pParagrafo;
	}
	
	public ParserRule getParagrafoRule() {
		return getParagrafoAccess().getRule();
	}
	
	//Inciso:
	//	('Inciso' | 'inciso') '(' texto=STRING ')' ('{'
	//	alineas+=Alinea*
	//	'}')?;
	public IncisoElements getIncisoAccess() {
		return pInciso;
	}
	
	public ParserRule getIncisoRule() {
		return getIncisoAccess().getRule();
	}
	
	//Alinea:
	//	('alinea' | 'Alinea') '(' texto=STRING ')' ('{'
	//	itens+=Item*
	//	'}')?;
	public AlineaElements getAlineaAccess() {
		return pAlinea;
	}
	
	public ParserRule getAlineaRule() {
		return getAlineaAccess().getRule();
	}
	
	//Item:
	//	('Item' | 'item') '(' texto=STRING ')';
	public ItemElements getItemAccess() {
		return pItem;
	}
	
	public ParserRule getItemRule() {
		return getItemAccess().getRule();
	}
	
	//Final:
	//	('Final' | 'final') '{'
	//	'}';
	public FinalElements getFinalAccess() {
		return pFinal;
	}
	
	public ParserRule getFinalRule() {
		return getFinalAccess().getRule();
	}
	
	//DataType:
	//	'datatype' name=ID;
	public DataTypeElements getDataTypeAccess() {
		return pDataType;
	}
	
	public ParserRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//Entity:
	//	'entity' name=ID ('extends' superType=[Entity])? '{'
	//	features+=Feature*
	//	'}';
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//Feature:
	//	many?='many'? name=ID ':' type=[Type];
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
