/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ufes.mdd.lei.LegisFacileRuntimeModule;
import ufes.mdd.lei.LegisFacileStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LegisFacileIdeSetup extends LegisFacileStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LegisFacileRuntimeModule(), new LegisFacileIdeModule()));
	}
	
}
