/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Artigo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ufes.mdd.lei.legisFacile.Artigo#getCaput <em>Caput</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.Artigo#getParagrafos <em>Paragrafos</em>}</li>
 * </ul>
 *
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getArtigo()
 * @model
 * @generated
 */
public interface Artigo extends EObject
{
  /**
   * Returns the value of the '<em><b>Caput</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Caput</em>' containment reference.
   * @see #setCaput(Caput)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getArtigo_Caput()
   * @model containment="true"
   * @generated
   */
  Caput getCaput();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Artigo#getCaput <em>Caput</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Caput</em>' containment reference.
   * @see #getCaput()
   * @generated
   */
  void setCaput(Caput value);

  /**
   * Returns the value of the '<em><b>Paragrafos</b></em>' containment reference list.
   * The list contents are of type {@link ufes.mdd.lei.legisFacile.Paragrafo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragrafos</em>' containment reference list.
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getArtigo_Paragrafos()
   * @model containment="true"
   * @generated
   */
  EList<Paragrafo> getParagrafos();

} // Artigo
