/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
