/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ementa</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ufes.mdd.lei.legisFacile.Ementa#getEmenta <em>Ementa</em>}</li>
 * </ul>
 *
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getEmenta()
 * @model
 * @generated
 */
public interface Ementa extends EObject
{
  /**
   * Returns the value of the '<em><b>Ementa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ementa</em>' attribute.
   * @see #setEmenta(String)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getEmenta_Ementa()
   * @model
   * @generated
   */
  String getEmenta();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Ementa#getEmenta <em>Ementa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ementa</em>' attribute.
   * @see #getEmenta()
   * @generated
   */
  void setEmenta(String value);

} // Ementa
