/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage
 * @generated
 */
public interface LegisFacileFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LegisFacileFactory eINSTANCE = ufes.mdd.lei.legisFacile.impl.LegisFacileFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Lei</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lei</em>'.
   * @generated
   */
  Lei createLei();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Preliminar</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Preliminar</em>'.
   * @generated
   */
  Preliminar createPreliminar();

  /**
   * Returns a new object of class '<em>Epigrafe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Epigrafe</em>'.
   * @generated
   */
  Epigrafe createEpigrafe();

  /**
   * Returns a new object of class '<em>Ementa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ementa</em>'.
   * @generated
   */
  Ementa createEmenta();

  /**
   * Returns a new object of class '<em>Preambulo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Preambulo</em>'.
   * @generated
   */
  Preambulo createPreambulo();

  /**
   * Returns a new object of class '<em>Normativa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Normativa</em>'.
   * @generated
   */
  Normativa createNormativa();

  /**
   * Returns a new object of class '<em>Artigo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artigo</em>'.
   * @generated
   */
  Artigo createArtigo();

  /**
   * Returns a new object of class '<em>Caput</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Caput</em>'.
   * @generated
   */
  Caput createCaput();

  /**
   * Returns a new object of class '<em>Paragrafo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Paragrafo</em>'.
   * @generated
   */
  Paragrafo createParagrafo();

  /**
   * Returns a new object of class '<em>Inciso</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inciso</em>'.
   * @generated
   */
  Inciso createInciso();

  /**
   * Returns a new object of class '<em>Alinea</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alinea</em>'.
   * @generated
   */
  Alinea createAlinea();

  /**
   * Returns a new object of class '<em>Item</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Item</em>'.
   * @generated
   */
  Item createItem();

  /**
   * Returns a new object of class '<em>Final</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Final</em>'.
   * @generated
   */
  Final createFinal();

  /**
   * Returns a new object of class '<em>Vigencia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vigencia</em>'.
   * @generated
   */
  Vigencia createVigencia();

  /**
   * Returns a new object of class '<em>Revogacao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Revogacao</em>'.
   * @generated
   */
  Revogacao createRevogacao();

  /**
   * Returns a new object of class '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Type</em>'.
   * @generated
   */
  DataType createDataType();

  /**
   * Returns a new object of class '<em>Entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity</em>'.
   * @generated
   */
  Entity createEntity();

  /**
   * Returns a new object of class '<em>Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Feature</em>'.
   * @generated
   */
  Feature createFeature();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LegisFacilePackage getLegisFacilePackage();

} //LegisFacileFactory
