/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ufes.mdd.lei.legisFacile.LegisFacileFactory
 * @model kind="package"
 * @generated
 */
public interface LegisFacilePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "legisFacile";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mdd.ufes/lei/LegisFacile";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "legisFacile";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LegisFacilePackage eINSTANCE = ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl.init();

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.LeiImpl <em>Lei</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.LeiImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getLei()
   * @generated
   */
  int LEI = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEI__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Lei</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEI_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.TypeImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Preliminar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__PRELIMINAR = 0;

  /**
   * The feature id for the '<em><b>Normativa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NORMATIVA = 1;

  /**
   * The feature id for the '<em><b>Final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__FINAL = 2;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.PreliminarImpl <em>Preliminar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.PreliminarImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreliminar()
   * @generated
   */
  int PRELIMINAR = 2;

  /**
   * The feature id for the '<em><b>Epigrage</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR__EPIGRAGE = 0;

  /**
   * The feature id for the '<em><b>Ementa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR__EMENTA = 1;

  /**
   * The feature id for the '<em><b>Preambulo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR__PREAMBULO = 2;

  /**
   * The number of structural features of the '<em>Preliminar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.EpigrafeImpl <em>Epigrafe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.EpigrafeImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEpigrafe()
   * @generated
   */
  int EPIGRAFE = 3;

  /**
   * The feature id for the '<em><b>Ato</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE__ATO = 0;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE__NUMERO = 1;

  /**
   * The feature id for the '<em><b>Ano</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE__ANO = 2;

  /**
   * The number of structural features of the '<em>Epigrafe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.EmentaImpl <em>Ementa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.EmentaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEmenta()
   * @generated
   */
  int EMENTA = 4;

  /**
   * The feature id for the '<em><b>Ementa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMENTA__EMENTA = 0;

  /**
   * The number of structural features of the '<em>Ementa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMENTA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.PreambuloImpl <em>Preambulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.PreambuloImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreambulo()
   * @generated
   */
  int PREAMBULO = 5;

  /**
   * The feature id for the '<em><b>Preambulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREAMBULO__PREAMBULO = 0;

  /**
   * The number of structural features of the '<em>Preambulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREAMBULO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.NormativaImpl <em>Normativa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.NormativaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getNormativa()
   * @generated
   */
  int NORMATIVA = 6;

  /**
   * The feature id for the '<em><b>Artigos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMATIVA__ARTIGOS = 0;

  /**
   * The number of structural features of the '<em>Normativa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMATIVA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.ArtigoImpl <em>Artigo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.ArtigoImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getArtigo()
   * @generated
   */
  int ARTIGO = 7;

  /**
   * The feature id for the '<em><b>Caput</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIGO__CAPUT = 0;

  /**
   * The feature id for the '<em><b>Paragrafos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIGO__PARAGRAFOS = 1;

  /**
   * The number of structural features of the '<em>Artigo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIGO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.CaputImpl <em>Caput</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.CaputImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getCaput()
   * @generated
   */
  int CAPUT = 8;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPUT__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Incisos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPUT__INCISOS = 1;

  /**
   * The number of structural features of the '<em>Caput</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.ParagrafoImpl <em>Paragrafo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.ParagrafoImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getParagrafo()
   * @generated
   */
  int PARAGRAFO = 9;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Incisos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO__INCISOS = 1;

  /**
   * The number of structural features of the '<em>Paragrafo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.IncisoImpl <em>Inciso</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.IncisoImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getInciso()
   * @generated
   */
  int INCISO = 10;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCISO__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Alineas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCISO__ALINEAS = 1;

  /**
   * The number of structural features of the '<em>Inciso</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCISO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.AlineaImpl <em>Alinea</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.AlineaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getAlinea()
   * @generated
   */
  int ALINEA = 11;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALINEA__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Itens</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALINEA__ITENS = 1;

  /**
   * The number of structural features of the '<em>Alinea</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALINEA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.ItemImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getItem()
   * @generated
   */
  int ITEM = 12;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__TEXTO = 0;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.FinalImpl <em>Final</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.FinalImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getFinal()
   * @generated
   */
  int FINAL = 13;

  /**
   * The feature id for the '<em><b>Vigencia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL__VIGENCIA = 0;

  /**
   * The feature id for the '<em><b>Revogacao</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL__REVOGACAO = 1;

  /**
   * The number of structural features of the '<em>Final</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.VigenciaImpl <em>Vigencia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.VigenciaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getVigencia()
   * @generated
   */
  int VIGENCIA = 14;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIGENCIA__TEXTO = 0;

  /**
   * The number of structural features of the '<em>Vigencia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIGENCIA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.RevogacaoImpl <em>Revogacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.RevogacaoImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getRevogacao()
   * @generated
   */
  int REVOGACAO = 15;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVOGACAO__TEXTO = 0;

  /**
   * The number of structural features of the '<em>Revogacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REVOGACAO_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Lei <em>Lei</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lei</em>'.
   * @see ufes.mdd.lei.legisFacile.Lei
   * @generated
   */
  EClass getLei();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Lei#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see ufes.mdd.lei.legisFacile.Lei#getElements()
   * @see #getLei()
   * @generated
   */
  EReference getLei_Elements();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see ufes.mdd.lei.legisFacile.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Type#getPreliminar <em>Preliminar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Preliminar</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getPreliminar()
   * @see #getType()
   * @generated
   */
  EReference getType_Preliminar();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Type#getNormativa <em>Normativa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Normativa</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getNormativa()
   * @see #getType()
   * @generated
   */
  EReference getType_Normativa();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Type#getFinal <em>Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Final</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getFinal()
   * @see #getType()
   * @generated
   */
  EReference getType_Final();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Preliminar <em>Preliminar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preliminar</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar
   * @generated
   */
  EClass getPreliminar();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Preliminar#getEpigrage <em>Epigrage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Epigrage</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar#getEpigrage()
   * @see #getPreliminar()
   * @generated
   */
  EReference getPreliminar_Epigrage();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Preliminar#getEmenta <em>Ementa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ementa</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar#getEmenta()
   * @see #getPreliminar()
   * @generated
   */
  EReference getPreliminar_Ementa();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Preliminar#getPreambulo <em>Preambulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Preambulo</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar#getPreambulo()
   * @see #getPreliminar()
   * @generated
   */
  EReference getPreliminar_Preambulo();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Epigrafe <em>Epigrafe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Epigrafe</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe
   * @generated
   */
  EClass getEpigrafe();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Epigrafe#getAto <em>Ato</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ato</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe#getAto()
   * @see #getEpigrafe()
   * @generated
   */
  EAttribute getEpigrafe_Ato();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Epigrafe#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe#getNumero()
   * @see #getEpigrafe()
   * @generated
   */
  EAttribute getEpigrafe_Numero();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Epigrafe#getAno <em>Ano</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ano</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe#getAno()
   * @see #getEpigrafe()
   * @generated
   */
  EAttribute getEpigrafe_Ano();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Ementa <em>Ementa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ementa</em>'.
   * @see ufes.mdd.lei.legisFacile.Ementa
   * @generated
   */
  EClass getEmenta();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Ementa#getEmenta <em>Ementa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ementa</em>'.
   * @see ufes.mdd.lei.legisFacile.Ementa#getEmenta()
   * @see #getEmenta()
   * @generated
   */
  EAttribute getEmenta_Ementa();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Preambulo <em>Preambulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preambulo</em>'.
   * @see ufes.mdd.lei.legisFacile.Preambulo
   * @generated
   */
  EClass getPreambulo();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Preambulo#getPreambulo <em>Preambulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Preambulo</em>'.
   * @see ufes.mdd.lei.legisFacile.Preambulo#getPreambulo()
   * @see #getPreambulo()
   * @generated
   */
  EAttribute getPreambulo_Preambulo();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Normativa <em>Normativa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normativa</em>'.
   * @see ufes.mdd.lei.legisFacile.Normativa
   * @generated
   */
  EClass getNormativa();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Normativa#getArtigos <em>Artigos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Artigos</em>'.
   * @see ufes.mdd.lei.legisFacile.Normativa#getArtigos()
   * @see #getNormativa()
   * @generated
   */
  EReference getNormativa_Artigos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Artigo <em>Artigo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Artigo</em>'.
   * @see ufes.mdd.lei.legisFacile.Artigo
   * @generated
   */
  EClass getArtigo();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Artigo#getCaput <em>Caput</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Caput</em>'.
   * @see ufes.mdd.lei.legisFacile.Artigo#getCaput()
   * @see #getArtigo()
   * @generated
   */
  EReference getArtigo_Caput();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Artigo#getParagrafos <em>Paragrafos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paragrafos</em>'.
   * @see ufes.mdd.lei.legisFacile.Artigo#getParagrafos()
   * @see #getArtigo()
   * @generated
   */
  EReference getArtigo_Paragrafos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Caput <em>Caput</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Caput</em>'.
   * @see ufes.mdd.lei.legisFacile.Caput
   * @generated
   */
  EClass getCaput();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Caput#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Caput#getTexto()
   * @see #getCaput()
   * @generated
   */
  EAttribute getCaput_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Caput#getIncisos <em>Incisos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Incisos</em>'.
   * @see ufes.mdd.lei.legisFacile.Caput#getIncisos()
   * @see #getCaput()
   * @generated
   */
  EReference getCaput_Incisos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Paragrafo <em>Paragrafo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paragrafo</em>'.
   * @see ufes.mdd.lei.legisFacile.Paragrafo
   * @generated
   */
  EClass getParagrafo();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Paragrafo#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Paragrafo#getTexto()
   * @see #getParagrafo()
   * @generated
   */
  EAttribute getParagrafo_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Paragrafo#getIncisos <em>Incisos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Incisos</em>'.
   * @see ufes.mdd.lei.legisFacile.Paragrafo#getIncisos()
   * @see #getParagrafo()
   * @generated
   */
  EReference getParagrafo_Incisos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Inciso <em>Inciso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inciso</em>'.
   * @see ufes.mdd.lei.legisFacile.Inciso
   * @generated
   */
  EClass getInciso();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Inciso#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Inciso#getTexto()
   * @see #getInciso()
   * @generated
   */
  EAttribute getInciso_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Inciso#getAlineas <em>Alineas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alineas</em>'.
   * @see ufes.mdd.lei.legisFacile.Inciso#getAlineas()
   * @see #getInciso()
   * @generated
   */
  EReference getInciso_Alineas();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Alinea <em>Alinea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alinea</em>'.
   * @see ufes.mdd.lei.legisFacile.Alinea
   * @generated
   */
  EClass getAlinea();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Alinea#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Alinea#getTexto()
   * @see #getAlinea()
   * @generated
   */
  EAttribute getAlinea_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Alinea#getItens <em>Itens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Itens</em>'.
   * @see ufes.mdd.lei.legisFacile.Alinea#getItens()
   * @see #getAlinea()
   * @generated
   */
  EReference getAlinea_Itens();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see ufes.mdd.lei.legisFacile.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Item#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Item#getTexto()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Texto();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Final <em>Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Final</em>'.
   * @see ufes.mdd.lei.legisFacile.Final
   * @generated
   */
  EClass getFinal();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Final#getVigencia <em>Vigencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vigencia</em>'.
   * @see ufes.mdd.lei.legisFacile.Final#getVigencia()
   * @see #getFinal()
   * @generated
   */
  EReference getFinal_Vigencia();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Final#getRevogacao <em>Revogacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Revogacao</em>'.
   * @see ufes.mdd.lei.legisFacile.Final#getRevogacao()
   * @see #getFinal()
   * @generated
   */
  EReference getFinal_Revogacao();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Vigencia <em>Vigencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vigencia</em>'.
   * @see ufes.mdd.lei.legisFacile.Vigencia
   * @generated
   */
  EClass getVigencia();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Vigencia#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Vigencia#getTexto()
   * @see #getVigencia()
   * @generated
   */
  EAttribute getVigencia_Texto();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Revogacao <em>Revogacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Revogacao</em>'.
   * @see ufes.mdd.lei.legisFacile.Revogacao
   * @generated
   */
  EClass getRevogacao();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Revogacao#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Revogacao#getTexto()
   * @see #getRevogacao()
   * @generated
   */
  EAttribute getRevogacao_Texto();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LegisFacileFactory getLegisFacileFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.LeiImpl <em>Lei</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.LeiImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getLei()
     * @generated
     */
    EClass LEI = eINSTANCE.getLei();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEI__ELEMENTS = eINSTANCE.getLei_Elements();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.TypeImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Preliminar</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__PRELIMINAR = eINSTANCE.getType_Preliminar();

    /**
     * The meta object literal for the '<em><b>Normativa</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__NORMATIVA = eINSTANCE.getType_Normativa();

    /**
     * The meta object literal for the '<em><b>Final</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__FINAL = eINSTANCE.getType_Final();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.PreliminarImpl <em>Preliminar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.PreliminarImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreliminar()
     * @generated
     */
    EClass PRELIMINAR = eINSTANCE.getPreliminar();

    /**
     * The meta object literal for the '<em><b>Epigrage</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRELIMINAR__EPIGRAGE = eINSTANCE.getPreliminar_Epigrage();

    /**
     * The meta object literal for the '<em><b>Ementa</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRELIMINAR__EMENTA = eINSTANCE.getPreliminar_Ementa();

    /**
     * The meta object literal for the '<em><b>Preambulo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRELIMINAR__PREAMBULO = eINSTANCE.getPreliminar_Preambulo();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.EpigrafeImpl <em>Epigrafe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.EpigrafeImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEpigrafe()
     * @generated
     */
    EClass EPIGRAFE = eINSTANCE.getEpigrafe();

    /**
     * The meta object literal for the '<em><b>Ato</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EPIGRAFE__ATO = eINSTANCE.getEpigrafe_Ato();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EPIGRAFE__NUMERO = eINSTANCE.getEpigrafe_Numero();

    /**
     * The meta object literal for the '<em><b>Ano</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EPIGRAFE__ANO = eINSTANCE.getEpigrafe_Ano();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.EmentaImpl <em>Ementa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.EmentaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEmenta()
     * @generated
     */
    EClass EMENTA = eINSTANCE.getEmenta();

    /**
     * The meta object literal for the '<em><b>Ementa</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMENTA__EMENTA = eINSTANCE.getEmenta_Ementa();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.PreambuloImpl <em>Preambulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.PreambuloImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreambulo()
     * @generated
     */
    EClass PREAMBULO = eINSTANCE.getPreambulo();

    /**
     * The meta object literal for the '<em><b>Preambulo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREAMBULO__PREAMBULO = eINSTANCE.getPreambulo_Preambulo();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.NormativaImpl <em>Normativa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.NormativaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getNormativa()
     * @generated
     */
    EClass NORMATIVA = eINSTANCE.getNormativa();

    /**
     * The meta object literal for the '<em><b>Artigos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMATIVA__ARTIGOS = eINSTANCE.getNormativa_Artigos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.ArtigoImpl <em>Artigo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.ArtigoImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getArtigo()
     * @generated
     */
    EClass ARTIGO = eINSTANCE.getArtigo();

    /**
     * The meta object literal for the '<em><b>Caput</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTIGO__CAPUT = eINSTANCE.getArtigo_Caput();

    /**
     * The meta object literal for the '<em><b>Paragrafos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTIGO__PARAGRAFOS = eINSTANCE.getArtigo_Paragrafos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.CaputImpl <em>Caput</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.CaputImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getCaput()
     * @generated
     */
    EClass CAPUT = eINSTANCE.getCaput();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAPUT__TEXTO = eINSTANCE.getCaput_Texto();

    /**
     * The meta object literal for the '<em><b>Incisos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAPUT__INCISOS = eINSTANCE.getCaput_Incisos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.ParagrafoImpl <em>Paragrafo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.ParagrafoImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getParagrafo()
     * @generated
     */
    EClass PARAGRAFO = eINSTANCE.getParagrafo();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAGRAFO__TEXTO = eINSTANCE.getParagrafo_Texto();

    /**
     * The meta object literal for the '<em><b>Incisos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAGRAFO__INCISOS = eINSTANCE.getParagrafo_Incisos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.IncisoImpl <em>Inciso</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.IncisoImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getInciso()
     * @generated
     */
    EClass INCISO = eINSTANCE.getInciso();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCISO__TEXTO = eINSTANCE.getInciso_Texto();

    /**
     * The meta object literal for the '<em><b>Alineas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INCISO__ALINEAS = eINSTANCE.getInciso_Alineas();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.AlineaImpl <em>Alinea</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.AlineaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getAlinea()
     * @generated
     */
    EClass ALINEA = eINSTANCE.getAlinea();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALINEA__TEXTO = eINSTANCE.getAlinea_Texto();

    /**
     * The meta object literal for the '<em><b>Itens</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALINEA__ITENS = eINSTANCE.getAlinea_Itens();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.ItemImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__TEXTO = eINSTANCE.getItem_Texto();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.FinalImpl <em>Final</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.FinalImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getFinal()
     * @generated
     */
    EClass FINAL = eINSTANCE.getFinal();

    /**
     * The meta object literal for the '<em><b>Vigencia</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL__VIGENCIA = eINSTANCE.getFinal_Vigencia();

    /**
     * The meta object literal for the '<em><b>Revogacao</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINAL__REVOGACAO = eINSTANCE.getFinal_Revogacao();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.VigenciaImpl <em>Vigencia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.VigenciaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getVigencia()
     * @generated
     */
    EClass VIGENCIA = eINSTANCE.getVigencia();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIGENCIA__TEXTO = eINSTANCE.getVigencia_Texto();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.RevogacaoImpl <em>Revogacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.RevogacaoImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getRevogacao()
     * @generated
     */
    EClass REVOGACAO = eINSTANCE.getRevogacao();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REVOGACAO__TEXTO = eINSTANCE.getRevogacao_Texto();

  }

} //LegisFacilePackage
