/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ufes.mdd.lei.legisFacile.LegisFacileFactory
 * @model kind="package"
 * @generated
 */
public interface LegisFacilePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "legisFacile";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mdd.ufes/lei/LegisFacile";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "legisFacile";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LegisFacilePackage eINSTANCE = ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl.init();

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.LeiImpl <em>Lei</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.LeiImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getLei()
   * @generated
   */
  int LEI = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEI__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Lei</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEI_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.TypeImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Preliminar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__PRELIMINAR = 0;

  /**
   * The feature id for the '<em><b>Normativa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NORMATIVA = 1;

  /**
   * The feature id for the '<em><b>Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__FINAL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 3;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.PreliminarImpl <em>Preliminar</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.PreliminarImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreliminar()
   * @generated
   */
  int PRELIMINAR = 2;

  /**
   * The feature id for the '<em><b>Epigrage</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR__EPIGRAGE = 0;

  /**
   * The feature id for the '<em><b>Ementa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR__EMENTA = 1;

  /**
   * The feature id for the '<em><b>Preambulo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR__PREAMBULO = 2;

  /**
   * The number of structural features of the '<em>Preliminar</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRELIMINAR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.EpigrafeImpl <em>Epigrafe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.EpigrafeImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEpigrafe()
   * @generated
   */
  int EPIGRAFE = 3;

  /**
   * The feature id for the '<em><b>Ato</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE__ATO = 0;

  /**
   * The feature id for the '<em><b>Numero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE__NUMERO = 1;

  /**
   * The feature id for the '<em><b>Ano</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE__ANO = 2;

  /**
   * The number of structural features of the '<em>Epigrafe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EPIGRAFE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.EmentaImpl <em>Ementa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.EmentaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEmenta()
   * @generated
   */
  int EMENTA = 4;

  /**
   * The feature id for the '<em><b>Ementa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMENTA__EMENTA = 0;

  /**
   * The number of structural features of the '<em>Ementa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMENTA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.PreambuloImpl <em>Preambulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.PreambuloImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreambulo()
   * @generated
   */
  int PREAMBULO = 5;

  /**
   * The feature id for the '<em><b>Preambulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREAMBULO__PREAMBULO = 0;

  /**
   * The number of structural features of the '<em>Preambulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREAMBULO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.NormativaImpl <em>Normativa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.NormativaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getNormativa()
   * @generated
   */
  int NORMATIVA = 6;

  /**
   * The feature id for the '<em><b>Artigos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMATIVA__ARTIGOS = 0;

  /**
   * The number of structural features of the '<em>Normativa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMATIVA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.ArtigoImpl <em>Artigo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.ArtigoImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getArtigo()
   * @generated
   */
  int ARTIGO = 7;

  /**
   * The feature id for the '<em><b>Caput</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIGO__CAPUT = 0;

  /**
   * The feature id for the '<em><b>Paragrafos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIGO__PARAGRAFOS = 1;

  /**
   * The number of structural features of the '<em>Artigo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIGO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.CaputImpl <em>Caput</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.CaputImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getCaput()
   * @generated
   */
  int CAPUT = 8;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPUT__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Paragrafos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPUT__PARAGRAFOS = 1;

  /**
   * The number of structural features of the '<em>Caput</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CAPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.ParagrafoImpl <em>Paragrafo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.ParagrafoImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getParagrafo()
   * @generated
   */
  int PARAGRAFO = 9;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Alineas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO__ALINEAS = 1;

  /**
   * The number of structural features of the '<em>Paragrafo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAGRAFO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.AlineaImpl <em>Alinea</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.AlineaImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getAlinea()
   * @generated
   */
  int ALINEA = 10;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALINEA__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Itens</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALINEA__ITENS = 1;

  /**
   * The number of structural features of the '<em>Alinea</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALINEA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.ItemImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getItem()
   * @generated
   */
  int ITEM = 11;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__TEXTO = 0;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.DataTypeImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 12;

  /**
   * The feature id for the '<em><b>Preliminar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__PRELIMINAR = TYPE__PRELIMINAR;

  /**
   * The feature id for the '<em><b>Normativa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NORMATIVA = TYPE__NORMATIVA;

  /**
   * The feature id for the '<em><b>Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__FINAL = TYPE__FINAL;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE__NAME = TYPE__NAME;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.EntityImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 13;

  /**
   * The feature id for the '<em><b>Preliminar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__PRELIMINAR = TYPE__PRELIMINAR;

  /**
   * The feature id for the '<em><b>Normativa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NORMATIVA = TYPE__NORMATIVA;

  /**
   * The feature id for the '<em><b>Final</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FINAL = TYPE__FINAL;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = TYPE__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FEATURES = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ufes.mdd.lei.legisFacile.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ufes.mdd.lei.legisFacile.impl.FeatureImpl
   * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 14;

  /**
   * The feature id for the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__MANY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TYPE = 2;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Lei <em>Lei</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lei</em>'.
   * @see ufes.mdd.lei.legisFacile.Lei
   * @generated
   */
  EClass getLei();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Lei#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see ufes.mdd.lei.legisFacile.Lei#getElements()
   * @see #getLei()
   * @generated
   */
  EReference getLei_Elements();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see ufes.mdd.lei.legisFacile.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Type#getPreliminar <em>Preliminar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Preliminar</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getPreliminar()
   * @see #getType()
   * @generated
   */
  EReference getType_Preliminar();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Type#getNormativa <em>Normativa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Normativa</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getNormativa()
   * @see #getType()
   * @generated
   */
  EReference getType_Normativa();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Type#getFinal <em>Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Final</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getFinal()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Final();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ufes.mdd.lei.legisFacile.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Preliminar <em>Preliminar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preliminar</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar
   * @generated
   */
  EClass getPreliminar();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Preliminar#getEpigrage <em>Epigrage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Epigrage</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar#getEpigrage()
   * @see #getPreliminar()
   * @generated
   */
  EReference getPreliminar_Epigrage();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Preliminar#getEmenta <em>Ementa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ementa</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar#getEmenta()
   * @see #getPreliminar()
   * @generated
   */
  EReference getPreliminar_Ementa();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Preliminar#getPreambulo <em>Preambulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Preambulo</em>'.
   * @see ufes.mdd.lei.legisFacile.Preliminar#getPreambulo()
   * @see #getPreliminar()
   * @generated
   */
  EReference getPreliminar_Preambulo();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Epigrafe <em>Epigrafe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Epigrafe</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe
   * @generated
   */
  EClass getEpigrafe();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Epigrafe#getAto <em>Ato</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ato</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe#getAto()
   * @see #getEpigrafe()
   * @generated
   */
  EAttribute getEpigrafe_Ato();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Epigrafe#getNumero <em>Numero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Numero</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe#getNumero()
   * @see #getEpigrafe()
   * @generated
   */
  EAttribute getEpigrafe_Numero();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Epigrafe#getAno <em>Ano</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ano</em>'.
   * @see ufes.mdd.lei.legisFacile.Epigrafe#getAno()
   * @see #getEpigrafe()
   * @generated
   */
  EAttribute getEpigrafe_Ano();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Ementa <em>Ementa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ementa</em>'.
   * @see ufes.mdd.lei.legisFacile.Ementa
   * @generated
   */
  EClass getEmenta();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Ementa#getEmenta <em>Ementa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ementa</em>'.
   * @see ufes.mdd.lei.legisFacile.Ementa#getEmenta()
   * @see #getEmenta()
   * @generated
   */
  EAttribute getEmenta_Ementa();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Preambulo <em>Preambulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preambulo</em>'.
   * @see ufes.mdd.lei.legisFacile.Preambulo
   * @generated
   */
  EClass getPreambulo();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Preambulo#getPreambulo <em>Preambulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Preambulo</em>'.
   * @see ufes.mdd.lei.legisFacile.Preambulo#getPreambulo()
   * @see #getPreambulo()
   * @generated
   */
  EAttribute getPreambulo_Preambulo();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Normativa <em>Normativa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normativa</em>'.
   * @see ufes.mdd.lei.legisFacile.Normativa
   * @generated
   */
  EClass getNormativa();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Normativa#getArtigos <em>Artigos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Artigos</em>'.
   * @see ufes.mdd.lei.legisFacile.Normativa#getArtigos()
   * @see #getNormativa()
   * @generated
   */
  EReference getNormativa_Artigos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Artigo <em>Artigo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Artigo</em>'.
   * @see ufes.mdd.lei.legisFacile.Artigo
   * @generated
   */
  EClass getArtigo();

  /**
   * Returns the meta object for the containment reference '{@link ufes.mdd.lei.legisFacile.Artigo#getCaput <em>Caput</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Caput</em>'.
   * @see ufes.mdd.lei.legisFacile.Artigo#getCaput()
   * @see #getArtigo()
   * @generated
   */
  EReference getArtigo_Caput();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Artigo#getParagrafos <em>Paragrafos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paragrafos</em>'.
   * @see ufes.mdd.lei.legisFacile.Artigo#getParagrafos()
   * @see #getArtigo()
   * @generated
   */
  EReference getArtigo_Paragrafos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Caput <em>Caput</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Caput</em>'.
   * @see ufes.mdd.lei.legisFacile.Caput
   * @generated
   */
  EClass getCaput();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Caput#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Caput#getTexto()
   * @see #getCaput()
   * @generated
   */
  EAttribute getCaput_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Caput#getParagrafos <em>Paragrafos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paragrafos</em>'.
   * @see ufes.mdd.lei.legisFacile.Caput#getParagrafos()
   * @see #getCaput()
   * @generated
   */
  EReference getCaput_Paragrafos();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Paragrafo <em>Paragrafo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Paragrafo</em>'.
   * @see ufes.mdd.lei.legisFacile.Paragrafo
   * @generated
   */
  EClass getParagrafo();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Paragrafo#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Paragrafo#getTexto()
   * @see #getParagrafo()
   * @generated
   */
  EAttribute getParagrafo_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Paragrafo#getAlineas <em>Alineas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Alineas</em>'.
   * @see ufes.mdd.lei.legisFacile.Paragrafo#getAlineas()
   * @see #getParagrafo()
   * @generated
   */
  EReference getParagrafo_Alineas();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Alinea <em>Alinea</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alinea</em>'.
   * @see ufes.mdd.lei.legisFacile.Alinea
   * @generated
   */
  EClass getAlinea();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Alinea#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Alinea#getTexto()
   * @see #getAlinea()
   * @generated
   */
  EAttribute getAlinea_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Alinea#getItens <em>Itens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Itens</em>'.
   * @see ufes.mdd.lei.legisFacile.Alinea#getItens()
   * @see #getAlinea()
   * @generated
   */
  EReference getAlinea_Itens();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see ufes.mdd.lei.legisFacile.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Item#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see ufes.mdd.lei.legisFacile.Item#getTexto()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Texto();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see ufes.mdd.lei.legisFacile.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see ufes.mdd.lei.legisFacile.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link ufes.mdd.lei.legisFacile.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see ufes.mdd.lei.legisFacile.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link ufes.mdd.lei.legisFacile.Entity#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see ufes.mdd.lei.legisFacile.Entity#getFeatures()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Features();

  /**
   * Returns the meta object for class '{@link ufes.mdd.lei.legisFacile.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see ufes.mdd.lei.legisFacile.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Feature#isMany <em>Many</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Many</em>'.
   * @see ufes.mdd.lei.legisFacile.Feature#isMany()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Many();

  /**
   * Returns the meta object for the attribute '{@link ufes.mdd.lei.legisFacile.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ufes.mdd.lei.legisFacile.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for the reference '{@link ufes.mdd.lei.legisFacile.Feature#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see ufes.mdd.lei.legisFacile.Feature#getType()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LegisFacileFactory getLegisFacileFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.LeiImpl <em>Lei</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.LeiImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getLei()
     * @generated
     */
    EClass LEI = eINSTANCE.getLei();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEI__ELEMENTS = eINSTANCE.getLei_Elements();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.TypeImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Preliminar</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__PRELIMINAR = eINSTANCE.getType_Preliminar();

    /**
     * The meta object literal for the '<em><b>Normativa</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__NORMATIVA = eINSTANCE.getType_Normativa();

    /**
     * The meta object literal for the '<em><b>Final</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__FINAL = eINSTANCE.getType_Final();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.PreliminarImpl <em>Preliminar</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.PreliminarImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreliminar()
     * @generated
     */
    EClass PRELIMINAR = eINSTANCE.getPreliminar();

    /**
     * The meta object literal for the '<em><b>Epigrage</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRELIMINAR__EPIGRAGE = eINSTANCE.getPreliminar_Epigrage();

    /**
     * The meta object literal for the '<em><b>Ementa</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRELIMINAR__EMENTA = eINSTANCE.getPreliminar_Ementa();

    /**
     * The meta object literal for the '<em><b>Preambulo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRELIMINAR__PREAMBULO = eINSTANCE.getPreliminar_Preambulo();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.EpigrafeImpl <em>Epigrafe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.EpigrafeImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEpigrafe()
     * @generated
     */
    EClass EPIGRAFE = eINSTANCE.getEpigrafe();

    /**
     * The meta object literal for the '<em><b>Ato</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EPIGRAFE__ATO = eINSTANCE.getEpigrafe_Ato();

    /**
     * The meta object literal for the '<em><b>Numero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EPIGRAFE__NUMERO = eINSTANCE.getEpigrafe_Numero();

    /**
     * The meta object literal for the '<em><b>Ano</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EPIGRAFE__ANO = eINSTANCE.getEpigrafe_Ano();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.EmentaImpl <em>Ementa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.EmentaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEmenta()
     * @generated
     */
    EClass EMENTA = eINSTANCE.getEmenta();

    /**
     * The meta object literal for the '<em><b>Ementa</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMENTA__EMENTA = eINSTANCE.getEmenta_Ementa();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.PreambuloImpl <em>Preambulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.PreambuloImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getPreambulo()
     * @generated
     */
    EClass PREAMBULO = eINSTANCE.getPreambulo();

    /**
     * The meta object literal for the '<em><b>Preambulo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREAMBULO__PREAMBULO = eINSTANCE.getPreambulo_Preambulo();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.NormativaImpl <em>Normativa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.NormativaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getNormativa()
     * @generated
     */
    EClass NORMATIVA = eINSTANCE.getNormativa();

    /**
     * The meta object literal for the '<em><b>Artigos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NORMATIVA__ARTIGOS = eINSTANCE.getNormativa_Artigos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.ArtigoImpl <em>Artigo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.ArtigoImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getArtigo()
     * @generated
     */
    EClass ARTIGO = eINSTANCE.getArtigo();

    /**
     * The meta object literal for the '<em><b>Caput</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTIGO__CAPUT = eINSTANCE.getArtigo_Caput();

    /**
     * The meta object literal for the '<em><b>Paragrafos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTIGO__PARAGRAFOS = eINSTANCE.getArtigo_Paragrafos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.CaputImpl <em>Caput</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.CaputImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getCaput()
     * @generated
     */
    EClass CAPUT = eINSTANCE.getCaput();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CAPUT__TEXTO = eINSTANCE.getCaput_Texto();

    /**
     * The meta object literal for the '<em><b>Paragrafos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CAPUT__PARAGRAFOS = eINSTANCE.getCaput_Paragrafos();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.ParagrafoImpl <em>Paragrafo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.ParagrafoImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getParagrafo()
     * @generated
     */
    EClass PARAGRAFO = eINSTANCE.getParagrafo();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAGRAFO__TEXTO = eINSTANCE.getParagrafo_Texto();

    /**
     * The meta object literal for the '<em><b>Alineas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAGRAFO__ALINEAS = eINSTANCE.getParagrafo_Alineas();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.AlineaImpl <em>Alinea</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.AlineaImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getAlinea()
     * @generated
     */
    EClass ALINEA = eINSTANCE.getAlinea();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALINEA__TEXTO = eINSTANCE.getAlinea_Texto();

    /**
     * The meta object literal for the '<em><b>Itens</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALINEA__ITENS = eINSTANCE.getAlinea_Itens();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.ItemImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__TEXTO = eINSTANCE.getItem_Texto();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.DataTypeImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.EntityImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FEATURES = eINSTANCE.getEntity_Features();

    /**
     * The meta object literal for the '{@link ufes.mdd.lei.legisFacile.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ufes.mdd.lei.legisFacile.impl.FeatureImpl
     * @see ufes.mdd.lei.legisFacile.impl.LegisFacilePackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Many</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__MANY = eINSTANCE.getFeature_Many();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__TYPE = eINSTANCE.getFeature_Type();

  }

} //LegisFacilePackage
