/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Preambulo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ufes.mdd.lei.legisFacile.Preambulo#getPreambulo <em>Preambulo</em>}</li>
 * </ul>
 *
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getPreambulo()
 * @model
 * @generated
 */
public interface Preambulo extends EObject
{
  /**
   * Returns the value of the '<em><b>Preambulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preambulo</em>' attribute.
   * @see #setPreambulo(String)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getPreambulo_Preambulo()
   * @model
   * @generated
   */
  String getPreambulo();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Preambulo#getPreambulo <em>Preambulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preambulo</em>' attribute.
   * @see #getPreambulo()
   * @generated
   */
  void setPreambulo(String value);

} // Preambulo
