/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Preliminar</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ufes.mdd.lei.legisFacile.Preliminar#getEpigrage <em>Epigrage</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.Preliminar#getEmenta <em>Ementa</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.Preliminar#getPreambulo <em>Preambulo</em>}</li>
 * </ul>
 *
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getPreliminar()
 * @model
 * @generated
 */
public interface Preliminar extends Type
{
  /**
   * Returns the value of the '<em><b>Epigrage</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Epigrage</em>' containment reference.
   * @see #setEpigrage(Epigrafe)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getPreliminar_Epigrage()
   * @model containment="true"
   * @generated
   */
  Epigrafe getEpigrage();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Preliminar#getEpigrage <em>Epigrage</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Epigrage</em>' containment reference.
   * @see #getEpigrage()
   * @generated
   */
  void setEpigrage(Epigrafe value);

  /**
   * Returns the value of the '<em><b>Ementa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ementa</em>' containment reference.
   * @see #setEmenta(Ementa)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getPreliminar_Ementa()
   * @model containment="true"
   * @generated
   */
  Ementa getEmenta();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Preliminar#getEmenta <em>Ementa</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ementa</em>' containment reference.
   * @see #getEmenta()
   * @generated
   */
  void setEmenta(Ementa value);

  /**
   * Returns the value of the '<em><b>Preambulo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preambulo</em>' containment reference.
   * @see #setPreambulo(Preambulo)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getPreliminar_Preambulo()
   * @model containment="true"
   * @generated
   */
  Preambulo getPreambulo();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Preliminar#getPreambulo <em>Preambulo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preambulo</em>' containment reference.
   * @see #getPreambulo()
   * @generated
   */
  void setPreambulo(Preambulo value);

} // Preliminar
