/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ufes.mdd.lei.legisFacile.Type#getPreliminar <em>Preliminar</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.Type#getNormativa <em>Normativa</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.Type#getFinal <em>Final</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.Type#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Preliminar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preliminar</em>' containment reference.
   * @see #setPreliminar(Preliminar)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getType_Preliminar()
   * @model containment="true"
   * @generated
   */
  Preliminar getPreliminar();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Type#getPreliminar <em>Preliminar</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preliminar</em>' containment reference.
   * @see #getPreliminar()
   * @generated
   */
  void setPreliminar(Preliminar value);

  /**
   * Returns the value of the '<em><b>Normativa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Normativa</em>' containment reference.
   * @see #setNormativa(Normativa)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getType_Normativa()
   * @model containment="true"
   * @generated
   */
  Normativa getNormativa();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Type#getNormativa <em>Normativa</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Normativa</em>' containment reference.
   * @see #getNormativa()
   * @generated
   */
  void setNormativa(Normativa value);

  /**
   * Returns the value of the '<em><b>Final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Final</em>' containment reference.
   * @see #setFinal(Final)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getType_Final()
   * @model containment="true"
   * @generated
   */
  Final getFinal();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Type#getFinal <em>Final</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Final</em>' containment reference.
   * @see #getFinal()
   * @generated
   */
  void setFinal(Final value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ufes.mdd.lei.legisFacile.LegisFacilePackage#getType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ufes.mdd.lei.legisFacile.Type#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Type
