/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LegisFacileUiModule extends AbstractLegisFacileUiModule {

	public LegisFacileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
