/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLegisFacileScopeProvider extends DelegatingScopeProvider {
}
