/**
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.legisFacile.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import ufes.mdd.lei.legisFacile.Final;
import ufes.mdd.lei.legisFacile.LegisFacilePackage;
import ufes.mdd.lei.legisFacile.Revogacao;
import ufes.mdd.lei.legisFacile.Vigencia;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Final</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ufes.mdd.lei.legisFacile.impl.FinalImpl#getVigencia <em>Vigencia</em>}</li>
 *   <li>{@link ufes.mdd.lei.legisFacile.impl.FinalImpl#getRevogacao <em>Revogacao</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FinalImpl extends MinimalEObjectImpl.Container implements Final
{
  /**
   * The cached value of the '{@link #getVigencia() <em>Vigencia</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVigencia()
   * @generated
   * @ordered
   */
  protected Vigencia vigencia;

  /**
   * The cached value of the '{@link #getRevogacao() <em>Revogacao</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRevogacao()
   * @generated
   * @ordered
   */
  protected Revogacao revogacao;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FinalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LegisFacilePackage.Literals.FINAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Vigencia getVigencia()
  {
    return vigencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVigencia(Vigencia newVigencia, NotificationChain msgs)
  {
    Vigencia oldVigencia = vigencia;
    vigencia = newVigencia;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LegisFacilePackage.FINAL__VIGENCIA, oldVigencia, newVigencia);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVigencia(Vigencia newVigencia)
  {
    if (newVigencia != vigencia)
    {
      NotificationChain msgs = null;
      if (vigencia != null)
        msgs = ((InternalEObject)vigencia).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LegisFacilePackage.FINAL__VIGENCIA, null, msgs);
      if (newVigencia != null)
        msgs = ((InternalEObject)newVigencia).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LegisFacilePackage.FINAL__VIGENCIA, null, msgs);
      msgs = basicSetVigencia(newVigencia, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LegisFacilePackage.FINAL__VIGENCIA, newVigencia, newVigencia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Revogacao getRevogacao()
  {
    return revogacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRevogacao(Revogacao newRevogacao, NotificationChain msgs)
  {
    Revogacao oldRevogacao = revogacao;
    revogacao = newRevogacao;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LegisFacilePackage.FINAL__REVOGACAO, oldRevogacao, newRevogacao);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRevogacao(Revogacao newRevogacao)
  {
    if (newRevogacao != revogacao)
    {
      NotificationChain msgs = null;
      if (revogacao != null)
        msgs = ((InternalEObject)revogacao).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LegisFacilePackage.FINAL__REVOGACAO, null, msgs);
      if (newRevogacao != null)
        msgs = ((InternalEObject)newRevogacao).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LegisFacilePackage.FINAL__REVOGACAO, null, msgs);
      msgs = basicSetRevogacao(newRevogacao, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LegisFacilePackage.FINAL__REVOGACAO, newRevogacao, newRevogacao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LegisFacilePackage.FINAL__VIGENCIA:
        return basicSetVigencia(null, msgs);
      case LegisFacilePackage.FINAL__REVOGACAO:
        return basicSetRevogacao(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LegisFacilePackage.FINAL__VIGENCIA:
        return getVigencia();
      case LegisFacilePackage.FINAL__REVOGACAO:
        return getRevogacao();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LegisFacilePackage.FINAL__VIGENCIA:
        setVigencia((Vigencia)newValue);
        return;
      case LegisFacilePackage.FINAL__REVOGACAO:
        setRevogacao((Revogacao)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LegisFacilePackage.FINAL__VIGENCIA:
        setVigencia((Vigencia)null);
        return;
      case LegisFacilePackage.FINAL__REVOGACAO:
        setRevogacao((Revogacao)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LegisFacilePackage.FINAL__VIGENCIA:
        return vigencia != null;
      case LegisFacilePackage.FINAL__REVOGACAO:
        return revogacao != null;
    }
    return super.eIsSet(featureID);
  }

} //FinalImpl
