/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LegisFacileAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ufes/mdd/lei/parser/antlr/internal/InternalLegisFacile.tokens");
	}
}
