/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ufes.mdd.lei.parser.antlr.internal.InternalLegisFacileParser;
import ufes.mdd.lei.services.LegisFacileGrammarAccess;

public class LegisFacileParser extends AbstractAntlrParser {

	@Inject
	private LegisFacileGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLegisFacileParser createParser(XtextTokenStream stream) {
		return new InternalLegisFacileParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Lei";
	}

	public LegisFacileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LegisFacileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
