/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ufes.mdd.lei.ui.internal.LeiActivator;

public class LegisFacileUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LeiActivator.getInstance().getInjector("ufes.mdd.lei.LegisFacile");
	}

}
