/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LegisFacileStandaloneSetup extends LegisFacileStandaloneSetupGenerated {

	public static void doSetup() {
		new LegisFacileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
