/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLegisFacileValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ufes.mdd.lei.legisFacile.LegisFacilePackage.eINSTANCE);
		return result;
	}
}
