/*
 * generated by Xtext 2.23.0
 */
package ufes.mdd.lei.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import ufes.mdd.lei.ui.internal.LeiActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LegisFacileExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LeiActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LeiActivator activator = LeiActivator.getInstance();
		return activator != null ? activator.getInjector(LeiActivator.UFES_MDD_LEI_LEGISFACILE) : null;
	}

}
